name: jk
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36075
title: JK
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#c2c2c2'
    - '#c1272d'
    - '#8f8f8f'
    - '#000000'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
